#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Marked } from 'marked';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const wiki = path.join(root, 'docs/wiki');
const pages = fs.readdirSync(wiki).filter(name => name.endsWith('.md') && !name.startsWith('_')).sort();
const escape = value => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const check = process.argv.includes('--check');
let changed = 0;

for (const name of pages) {
  const headings = [];
  const ids = new Map();
  const markdown = fs.readFileSync(path.join(wiki, name), 'utf8');
  const title = markdown.match(/^# (.+)/m)?.[1] || name.slice(0, -3);
  const parser = new Marked({ gfm: true });
  parser.use({ renderer: {
    heading({ tokens, depth }) {
      const text = this.parser.parseInline(tokens);
      const base = text.replace(/<[^>]*>/g, '').toLowerCase().replace(/[^\p{L}\p{N}_\-\s]/gu, '').replace(/\s/g, '-');
      const count = ids.get(base) || 0;
      ids.set(base, count + 1);
      const id = count ? `${base}-${count}` : base;
      if (depth === 2) headings.push({ id, text });
      return `<h${depth} id="${escape(id)}">${text}</h${depth}>\n`;
    },
    link({ href, title, tokens }) {
      if (!/^(?:https?:|mailto:|#)/i.test(href)) {
        const [target, fragment] = href.split('#');
        const file = path.resolve(wiki, target);
        if (path.dirname(file) === wiki && pages.includes(path.basename(file))) {
          href = target.replace(/\.md$/, '.html') + (fragment === undefined ? '' : `#${fragment}`);
        } else if (target.endsWith('.md') || !file.startsWith(path.join(root, 'docs') + path.sep)) {
          const relative = path.relative(root, file).split(path.sep).map(encodeURIComponent).join('/');
          href = `https://github.com/BrandedTamarasu-glitch/ForgeFlow/blob/main/${relative}` + (fragment === undefined ? '' : `#${fragment}`);
        }
      }
      if (!/^(?:https?:|mailto:|#|\.?\.?\/|[\w-])/i.test(href) || /^(?:javascript|data|vbscript):/i.test(href)) return this.parser.parseInline(tokens);
      return `<a href="${escape(href)}"${title ? ` title="${escape(title)}"` : ''}>${this.parser.parseInline(tokens)}</a>`;
    },
    html({ text }) { return escape(text); }
  } });
  const body = parser.parse(markdown).replace(/<table>/g, '<div class="table-wrap"><table>').replace(/<\/table>/g, '</table></div>');
  const toc = headings.map(h => `<li><a href="#${escape(h.id)}">${h.text}</a></li>`).join('');
  const html = `<!doctype html>
<!-- Generated by scripts/build-docs.mjs. Edit ${name} and docs/guide.css. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)} · ForgeFlow</title><link rel="icon" type="image/png" sizes="32x32" href="../assets/forge-flame-icon-32.png"><link rel="icon" type="image/svg+xml" sizes="any" href="../assets/forge-flame-icon.svg"><link rel="stylesheet" href="../guide.css"></head>
<body><a class="skip" href="#main">Skip to content</a><header class="toolbar"><a class="brand" href="../index.html"><img src="../assets/logos/forge-flame.svg" alt="" width="30" height="34">ForgeFlow<span> / User guide</span></a><nav aria-label="Main navigation"><a href="../documentation.html">Documentation</a><a href="../user-guide.html">Visual walkthrough</a><a href="Home.html">All topics</a></nav></header>
<div class="guide-layout"><aside><nav aria-label="On this page"><p class="eyebrow">On this page</p><ul>${toc}</ul></nav><a class="source" href="${name}">Markdown source</a></aside><main id="main" class="guide-page"><p class="eyebrow">ForgeFlow / Reference</p>${body}<footer><a href="Home.html">← All guide topics</a><a href="../user-guide.html">Visual walkthrough →</a></footer></main></div></body></html>
`;
  const out = path.join(wiki, name.replace(/\.md$/, '.html'));
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== html) {
    changed++;
    if (!check) fs.writeFileSync(out, html);
  }
}
if (check && changed) throw new Error(`${changed} guide pages need rebuilding. Run npm run docs:build.`);
console.log(`${pages.length} guide pages; ${changed} ${check ? 'out of date' : 'updated'}.`);
